// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cltcekuvmcoylzgrqixf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsdGNla3V2bWNveWx6Z3JxaXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTQyMTEsImV4cCI6MjA2MDgzMDIxMX0.iPtIq8VRCH2Fay8NSpA5EJuIRvSUGZYBuGG72yXdZ-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);